import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { ShieldAlert, DollarSign, Calendar, MessageSquare, Briefcase, User, TrendingUp, Clock } from 'lucide-react';
import { LoadingSpinner } from './LoadingState';

export const CampaignsPage: React.FC = () => {
  const { getAuthHeaders } = useAuth();
  const [campaigns, setCampaigns] = useState<any[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [selectedCampaign, setSelectedCampaign] = useState<any>(null);

  const fetchCampaigns = async () => {
    setIsLoading(true);
    try {
      const headers = getAuthHeaders();
      const res = await fetch('/api/campaigns', { headers });
      if (res.ok) {
        const data = await res.json();
        setCampaigns(data);
        if (data.length > 0) {
          setSelectedCampaign(data[0]);
        }
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchCampaigns();
  }, []);

  if (isLoading) {
    return (
      <div className="flex-1 flex items-center justify-center bg-[#faf9f8] dark:bg-[#11100f] h-screen">
        <LoadingSpinner />
      </div>
    );
  }

  return (
    <div className="flex-1 flex overflow-hidden h-[calc(100vh-57px)] bg-[#faf9f8] dark:bg-[#11100f]">
      {/* Left List Pane */}
      <div className="w-96 border-r border-microsoft-border dark:border-zinc-850 flex flex-col bg-white dark:bg-[#201f1e] overflow-y-auto">
        <div className="p-6 border-b border-microsoft-border dark:border-zinc-800">
          <h2 className="font-bold text-sm dark:text-white flex items-center gap-2">
            <ShieldAlert className="w-5 h-5 text-risk-high" />
            <span>Revenue Rescue Campaigns</span>
          </h2>
          <p className="text-[10px] text-gray-400 mt-1.5 uppercase tracking-wider">Active Attrition Controls ({campaigns.length})</p>
        </div>

        <div className="divide-y divide-microsoft-border dark:divide-zinc-800">
          {campaigns.map((camp) => (
            <button
              key={camp.id}
              onClick={() => setSelectedCampaign(camp)}
              className={`w-full text-left p-6 transition-all border-l-4 ${
                selectedCampaign?.id === camp.id
                  ? 'bg-microsoft-lightBlue/30 dark:bg-blue-950/15 border-microsoft-blue'
                  : 'hover:bg-gray-50 dark:hover:bg-zinc-850 border-transparent'
              }`}
            >
              <div className="flex justify-between items-start">
                <span className="font-bold text-xs text-microsoft-charcoal dark:text-white truncate block max-w-[180px]">
                  {camp.customer_name}
                </span>
                <span className="text-[10px] font-bold text-risk-high bg-red-50 dark:bg-red-950/20 px-1.5 py-0.5 rounded uppercase">
                  Active
                </span>
              </div>
              <p className="text-[10px] text-gray-400 mt-1">Net Recovery Value: <span className="font-semibold text-risk-low">${camp.net_recovery_value.toLocaleString()}</span></p>
              <div className="mt-3 flex justify-between text-[11px] text-gray-500 dark:text-zinc-400">
                <span>Protected: ${camp.estimated_revenue_protected.toLocaleString()}</span>
                <span className="italic text-[9px] text-gray-400">Created: {new Date(camp.created_at).toLocaleDateString()}</span>
              </div>
            </button>
          ))}
          {campaigns.length === 0 && (
            <div className="p-6 text-center text-xs text-gray-400 dark:text-zinc-500 italic">
              No active rescue campaigns. Run portfolio assessments for high-risk accounts to auto-generate.
            </div>
          )}
        </div>
      </div>

      {/* Right Details Pane */}
      {selectedCampaign ? (
        <div className="flex-1 p-8 overflow-y-auto space-y-6">
          <div className="flex justify-between items-start border-b border-microsoft-border dark:border-zinc-800 pb-6">
            <div>
              <h1 className="text-xl font-bold dark:text-white">{selectedCampaign.customer_name} - Rescue Campaign</h1>
              <p className="text-xs text-gray-400 mt-1">Tailored recovery orchestration generated by AI Agents</p>
            </div>
            
            <div className="flex gap-4">
              <div className="bg-[#faf9f8] dark:bg-zinc-900 border border-microsoft-border dark:border-zinc-800 rounded px-4 py-2 text-center shadow-sm">
                <span className="text-[9px] font-bold uppercase tracking-wider text-gray-400 block">Revenue Protected</span>
                <span className="text-sm font-bold text-microsoft-charcoal dark:text-white">${selectedCampaign.estimated_revenue_protected.toLocaleString()}</span>
              </div>
              <div className="bg-[#faf9f8] dark:bg-zinc-900 border border-microsoft-border dark:border-zinc-800 rounded px-4 py-2 text-center shadow-sm">
                <span className="text-[9px] font-bold uppercase tracking-wider text-gray-400 block">Execution Cost</span>
                <span className="text-sm font-bold text-risk-medium">${selectedCampaign.estimated_execution_cost.toLocaleString()}</span>
              </div>
              <div className="bg-[#faf9f8] dark:bg-zinc-900 border border-microsoft-border dark:border-zinc-800 rounded px-4 py-2 text-center shadow-sm border-l-4 border-l-risk-low">
                <span className="text-[9px] font-bold uppercase tracking-wider text-gray-400 block">Net Recovery ROI</span>
                <span className="text-sm font-bold text-risk-low">${selectedCampaign.net_recovery_value.toLocaleString()}</span>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Strategy Cards */}
            <div className="space-y-6">
              <div className="glass-panel p-6 border-t-4 border-microsoft-blue space-y-3">
                <h3 className="text-xs font-bold uppercase tracking-wider text-microsoft-blue flex items-center gap-2">
                  <User className="w-4 h-4" />
                  <span>Executive Escalation Briefing</span>
                </h3>
                <p className="text-xs leading-normal text-microsoft-charcoal dark:text-zinc-300">
                  {selectedCampaign.executive_recommendation}
                </p>
              </div>

              <div className="glass-panel p-6 border-t-4 border-risk-low space-y-3">
                <h3 className="text-xs font-bold uppercase tracking-wider text-risk-low flex items-center gap-2">
                  <Clock className="w-4 h-4" />
                  <span>Customer Success Action Plan</span>
                </h3>
                <p className="text-xs leading-normal text-microsoft-charcoal dark:text-zinc-300">
                  {selectedCampaign.customer_success_plan}
                </p>
              </div>

              <div className="glass-panel p-6 border-t-4 border-risk-medium space-y-3">
                <h3 className="text-xs font-bold uppercase tracking-wider text-risk-medium flex items-center gap-2">
                  <DollarSign className="w-4 h-4" />
                  <span>Finance Collection Mediation</span>
                </h3>
                <p className="text-xs leading-normal text-microsoft-charcoal dark:text-zinc-300">
                  {selectedCampaign.finance_plan}
                </p>
              </div>

              <div className="glass-panel p-6 border-t-4 border-purple-500 space-y-3">
                <h3 className="text-xs font-bold uppercase tracking-wider text-purple-500 flex items-center gap-2">
                  <Calendar className="w-4 h-4" />
                  <span>Contract Renewal Strategy</span>
                </h3>
                <p className="text-xs leading-normal text-microsoft-charcoal dark:text-zinc-300">
                  {selectedCampaign.renewal_strategy}
                </p>
              </div>
            </div>

            {/* Timeline Column */}
            <div className="glass-panel p-6 flex flex-col">
              <div className="flex items-center gap-2 border-b border-microsoft-border dark:border-zinc-800 pb-4 mb-4">
                <Clock className="w-4 h-4 text-microsoft-blue" />
                <h3 className="text-xs font-bold uppercase tracking-wider dark:text-white">Suggested Outreach Timeline</h3>
              </div>
              
              <div className="flex-1 space-y-6 relative before:absolute before:left-3 before:top-2 before:bottom-2 before:w-[2px] before:bg-gray-200 dark:before:bg-zinc-800">
                {selectedCampaign.outreach_timeline?.map((step: any, idx: number) => (
                  <div key={idx} className="flex gap-4 relative z-10">
                    <div className="w-6 h-6 rounded-full bg-microsoft-blue text-white flex items-center justify-center text-[10px] font-bold shadow-sm shrink-0">
                      {step.step}
                    </div>
                    <div className="bg-[#faf9f8] dark:bg-zinc-900/60 p-4 rounded border border-microsoft-border dark:border-zinc-800 flex-1 space-y-1">
                      <div className="flex justify-between items-center">
                        <span className="font-bold text-xs dark:text-white">{step.action}</span>
                        <span className="text-[10px] font-semibold text-microsoft-blue bg-blue-50 dark:bg-blue-950/20 px-2 py-0.5 rounded">
                          {step.timeframe}
                        </span>
                      </div>
                      <p className="text-[11px] text-gray-500 dark:text-zinc-400 leading-normal">
                        {step.description}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      ) : (
        <div className="flex-1 flex flex-col items-center justify-center text-gray-400 dark:text-zinc-600">
          <ShieldAlert className="w-12 h-12 mb-2" />
          <p className="text-sm font-semibold">Select a rescue campaign to view outreach plan.</p>
        </div>
      )}
    </div>
  );
};
